### ISSUE TITLE
Implement support in systemd-resolved

### ISSUE THREAD

**Issue by lathiat** [avahi/avahi#132]
Since name resolution seems to be heading down the system-resolved path even in Ubuntu, we should contribute a patch to support resolution via Avahi.

They presently seem to have some very rudimentary support for mDNS but is usually disabled and LLMNR is recommended for normal hostname lookups.

D-Bus is already inside resolved so this should be easy.

**Comment by evverx** [comment]
@lathiat I think it can be closed. The mDNS part of resolved is generally advertised as a way to replace avahi and to judge from things like https://daenney.github.io/2021/11/14/replacing-avahi-exploring-dnssd/ and https://media.ccc.de/v/all-systems-go-2024-297-can-systemd-resolved-replace-avahi- that sort of advertisement works. The resolved documentation already claims that MulticastDNS= enables full Multicast DNS responder and resolver support (which is not exactly accurate given that a lot of things like browsing, known answer suppression and so on aren't implemented at all (and that's why "Replacing Avahi part 3" has never been published and is unlikely to be published anytime soon) and the parts that are implemented usually violate the RFC and/or incoherent) but the documentation looks convincing enough apparently.

> D-Bus is already inside resolved so this should be easy.

Its primary interface is varlink these days and, for example, the PR where continuous queries are being implemented doesn't provide the D-Bus API at all. I'm not sure if it's going to change or not. That PR has been reviewed since the beginning of 2022 as far as I can remember and it still violates the RFC and probably crashes.

Either way I'll go ahead and close the issue as not-planned.
