### ISSUE TITLE
For multiple interfaces on one sub-net, advertise the address with the preferred route metric

### ISSUE THREAD

**Issue by cmcqueen** [avahi/avahi#331]
Eg a machine might have Ethernet and Wi-Fi both connected to the same sub-net. In the routing table, the machine will prefer to use the interface with the lower value for "metric" (most likely Ethernet).

It would be ideal for avahi to advertise the address that is on the preferred interface for routing.

On the machine I'm currently using (an embedded Linux device) with both Ethernet and Wi-Fi, avahi is advertising the Wi-Fi IP address, but it would be more sensible to advertise the Ethernet address.

If it's too hard for avahi to work it out from the routing table (which I suppose might be true for more complex routing tables), then it would be good to have a config option to specify interface preference order for this scenario.

**Comment by evverx** [comment]
According to https://datatracker.ietf.org/doc/html/rfc6762#section-6.2
> When a Multicast DNS responder sends a Multicast DNS response message
   containing its own address records, it MUST include all addresses
   that are valid on the interface on which it is sending the message,
   and MUST NOT include addresses that are not valid on that interface
   (such as addresses that may be configured on the host's other
   interfaces).

so that queries can make can make their own choice. It's not how avahi works currently but it's (partly) tracked in https://github.com/avahi/avahi/issues/243.
