### ISSUE TITLE
[Question] Get TTL value when resolving a service using avahi-client API

### ISSUE THREAD

**Issue by superwhd** [avahi/avahi#344]
Hi there,

I'm implementing a discovery proxy using avahi-client API. It seems in the [AvahiServiceResolverCallback](https://avahi.org/doxygen/html/lookup_8h.html#a0b7bac822388d7c8197cbdc482e58523), I'm not able to get TTL information directly. What is the suggested way to retrieve TTL using avahi API? Thanks!

**Comment by hyh19962008** [comment]
try avahi_server_iterate() to check all the records.

**Comment by evverx** [comment]
Unfortunately TTLs aren't exposed via the avahi-client API. The avahi-core API can be used instead (but full resource records are explicitly passed to record browser callbacks only and service browsers/resolvers don't see them there either so browsers/resolvers with TTLs should probably be built on top of record browsers).

Just out of curiosity looking at https://github.com/openthread/ot-br-posix/pull/868 I wonder how the ot-br-posix project got this limitation around or did TTLs end up not being needed in the end?

**Comment by hyh19962008** [comment]
We use mDNS as a failover solution so we need to set TTL to 2s instead of 2 minutes when publish a service. So we created a fork [hyh19962008/avahi](https://github.com/hyh19962008/avahi) to add an API "avahi_entry_group_add_service_ttl" in publish.h.

**Comment by evverx** [comment]
Got it. avahi currently follows https://datatracker.ietf.org/doc/html/rfc6762#section-10 when RRs are published and it's unlikely to change.

The problem is that https://datatracker.ietf.org/doc/html/rfc6762#section-10.4 isn't implemented so there is no way to delete stale cache entries if devices go down without sending goodbye packets for whatever reason.

**Comment by evverx** [comment]
I think this issue can be closed because TTLs are unlikely to be exposed via the avahi-client API.

**Comment by hyh19962008** [comment]
> Got it. avahi currently follows https://datatracker.ietf.org/doc/html/rfc6762#section-10 when RRs are published and it's unlikely to change.
> 
> The problem is that https://datatracker.ietf.org/doc/html/rfc6762#section-10.4 isn't implemented so there is no way to delete stale cache entries if devices go down without sending goodbye packets for whatever reason.

Thanks for informing about section-10.4, so far TTL expiry with 2s is good enough for us.

**Comment by evverx** [comment]
FWIW the Reconfirm method (implementing 10.4 and inspired by mDNSResponder) was proposed in https://github.com/avahi/avahi/pull/229 so with that PR applied it's possible to remove stale resource records from the cache. Until it's merged it's necessary to get it around by either publishing RRs with short TTLs or in the case of the avahi reflector turning off the cache entirely to prevent it from caching stale stuff.

**Comment by hyh19962008** [comment]
Is it OK to create a PR of my fork which adds an API to set TTL? I think RFC6762 does not restrict user to set their own TTL, only provides recommended values.

**Comment by evverx** [comment]
> I think RFC6762 does not restrict user to set their own TTL, only provides recommended values

That's correct but I'm not sure it should be configurable either because it makes it relatively easy to misconfigure things. For example as mentioned in the RFC
> Making the default RR TTL significantly lower
   would reduce the lifetime of stale data, but would produce too much
   extra traffic on the network

> Is it OK to create a PR of my fork which adds an API to set TTL?

PRs are generally always welcome but it would be great if you could add tests (as far as I can see there are no tests covering `avahi_entry_group_add_service_strlst_ttl` at the moment) and also expand on what the use cases is. I took a quick look at that commit and to me it seems it covers a niche use case and I'm not sure whether it should be included upstream. (I'm not sure why it would be necessary to publish a service where its goodbye packet is sent in, say, 2 seconds removing it from all the mDNS caches on the network).

Other than that TTLs are inconsistent in that only SRV RRs are affected as far as I can see:
```sh
TestA._qotd._tcp.local. 1       IN      SRV     0 0 123 H.local.
H.local.        10      IN      A       192.168.56.4
TestA._qotd._tcp.local. 10      IN      TXT     ""
```
avahi logs something like
```
Received record with bad TTL [TestY._qotd._tcp.local    IN      SRV 0 0 123 H.local ; ttl=1]. Refreshing.
Received record with bad TTL [TestY._qotd._tcp.local    IN      SRV 0 0 123 H.local ; ttl=1]. Refreshing.
```
and so on.
