### ISSUE TITLE
Need some checks run on each PR

### ISSUE THREAD

**Issue by pemensik** [avahi/avahi#412]
I think we want to have some CI integrated in Avahi. There is quite a lot to improve. A solid test suite would be ideally run on every PR, but we can gradually improve it. For a start it would be nice to ensure changes compile on different systems. Like Fedora, CentOS, Debian stable, Debian sid, Ubuntu LTS. Maybe others. I can certainly bootstrap something related to Fedora and CentOS. Have not done it before, but we have many people involved in such thing.

**Comment by pemensik** [comment]
There is already some candidate. I am not sure what exactly it does, but could be a good starting point:
- https://github.com/lathiat/avahi/pull/382

**Comment by evverx** [comment]
Anyway I opened https://github.com/lathiat/avahi/pull/413 to cover some basic stuff. It was tested in https://github.com/evverx/avahi/pull/2. Eventually it can be extended by adding `dfuzzer` to catch issues like https://github.com/lathiat/avahi/issues/375 and `radamsa` to catch issues like https://github.com/lathiat/avahi/pull/330 and https://github.com/lathiat/avahi/issues/338.

**Comment by evverx** [comment]
> Looks like GHActions aren't enabled here

Having said that it they were fully turned off the "actions" tab would be hidden as well. It could be https://github.com/lathiat/avahi/pull/413 wasn't run because it's the first PR here with the ".github/workflow" directory and once it's merged GHActions should start working. It's hard to tell without any way to look at the actions settings.

**Comment by pemensik** [comment]
I would recommend using cmocka library for unit tests. It is kind of minimalistic and nice enough.

**Comment by pemensik** [comment]
I think the problem is we kind of want emulate handling network responses, which current tests do not do. I think it lacks also nice way to report failed assertions. That is what cmocka is good about. I think just generates list of executables to run on make check.

I think a container running own dbus instance and avahi, for example running in separate network namespace, might work. Have been thinking about something similar for dnsmasq, which does not have library prepared enough just for unit testing. Functional tests would be nice too, but not sure how difficult actions can we do in those actions.

**Comment by evverx** [comment]
> I think the problem is we kind of want emulate handling network responses, which current tests do not do

Agreed.

> I think a container running own dbus instance and avahi, for example running in separate network namespace, might work

Agreed. To get avahi to not reject some packets there should be a way to create local networks. Unfortunately last time I tried to do something like that using GHActions it didn't work out. It was a long time ago though.

All in all I think covering avahi with tests from scratch is kind of hard and probably can take a while. Until then it should be possible to pick the low-hanging fruit to mostly make sure that PRs don't break builds at least. Apart from https://github.com/lathiat/avahi/pull/413 I think it would be great to build avahi on various architectures and I already started building it on Packit on PRs: https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-1/build/5079690/. It's a one-file change but someone with admin access should hook up the repository to Packit.

**Comment by evverx** [comment]
I got Packit to compile avahi on PRs on `aarch64`, `i386`, `ppc64le`, `s390x` and `x86_64` by editing the Fedora spec file in various places. @pemensik since you are a maintainer of the package I wonder why it's compiled without `--enable-tests` and `make check` isn't run there? I'm asking because I'm planning to run more existing unit tests automatically with `make check` to make the coverage go from 3% (https://coveralls.io/builds/54821508) to almost 10% (https://coveralls.io/builds/54825736) and want to make sure that they don't break anything. I already tested that extended testsuite in https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-1/build/5081493/ but it could be I'm missing something.

On a somewhat related note the package fails to compile on Packit with
```sh
    # RPM build errors:
    # line 366: It's not recommended to have unversioned Obsoletes: Obsoletes:        howl-libs
    # line 376: It's not recommended to have unversioned Obsoletes: Obsoletes:        howl-devel
```
I got it around but it should probably be fixed in the spec file.

**Comment by evverx** [comment]
In case anyone is interested Avahi is on Coverity Scan now: https://scan.coverity.com/projects/avahi-daemon. I built and sent it there manually but hopefully I can bring an action sending it there automatically (for it to work the repository settings should be tweaked to add the coverity token to the COVERITY_SCAN_TOKEN secret: https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by evverx** [comment]
It would be great to get https://github.com/lathiat/avahi/pull/425 merged. I think in general compilers should be the first line of defence before any tests are run.

**Comment by evverx** [comment]
I think this issue can be closed. I'll open a separate issue to keep track of Packit, Coveralls and Coverity. The scripts and actions are ready but the repository has to be set up.
