### ISSUE TITLE
autoipd: Please support dhcpcd

### ISSUE THREAD

**Issue by bdrung** [avahi/avahi#467]
ISC has [announced](https://www.isc.org/dhcp/) the end of life for ISC DHCP as of the end of 2022. Kea is the recommended successor of the DHCP server. This bug report is about replacing the DHCP client `dhclient`. autoipd ships [dhclient-enter-hook.in](https://github.com/lathiat/avahi/blob/master/avahi-autoipd/dhclient-enter-hook.in) and [dhclient-exit-hook.in](https://github.com/lathiat/avahi/blob/master/avahi-autoipd/dhclient-exit-hook.in) for it.

Please provide similar hooks for [dhcpcd](https://roy.marples.name/projects/dhcpcd) to allow user to use dhcpcd as replacement for dhclient. Debian and Ubuntu want to migrate from dhclient to dhcpcd.

**Comment by pemensik** [comment]
Primary way to handle DHCP on Fedora and RHEL is Network Manager. Alternative is systemd-networkd. dhcpcd is possible as well, but pull request would be welcome.
I happen to be dhcpcd maintainer on Fedora, but I have never used it myself. It would be better if anyone actually using it could test the implementation. I am not against, but not sure how much this is required.

**Comment by evverx** [comment]
I've just taken a look at https://roy.marples.name/projects/dhcpcd and it supports IPv4LL out of the box so there is no need to hook it up to avahi-autoipd in the first place.
```sh
host0: soliciting a DHCP lease                                                                                                                                
host0: sending DISCOVER (xid 0x190c595a), next in 4.8 seconds                                                                                                 
host0: ARP probing 169.254.132.242 (2 of 3), next in 1.3 seconds                                                                                              
host0: Router Advertisement from fe80::34d2:13ff:fed2:dd9e                                                                                                    
host0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT                                                                                                  
Dropped protocol specifier '.ra' from 'host0.ra'. Using 'host0' (ifindex=2).                                                                                  
host0: ARP probing 169.254.132.242 (3 of 3), next in 2.0 seconds                                                                                              
host0: using IPv4LL address 169.254.132.242           
```
Closing.

**Comment by pemensik** [comment]
I think such support should be done on dhcpcd project, if needed. But I agree, this should be better done not by avahi itself, but whatever network configuration service is used. If dhcpcd can configure it directly, it may have ability to notify us about that, unless existing interface address changes can already catch everything needed.

If something more special is needed, please create new issue requesting missing pieces on avahi side explicitly. We barely can improve avahi, making improvements for other projects is not good idea until that changes.

**Comment by evverx** [comment]
The dhcpcd package already says that it provides `avahi-autoipd`: https://salsa.debian.org/debian/dhcpcd/-/commit/aacee2c6fd229f84833c0f62d66287d147619662.

(When I ran it it got accidentally hit by my fuzzer (unrelated to IPv4LL) https://github.com/NetworkConfiguration/dhcpcd/issues/415 and that issue was almost immediately fixed so the project is clearly maintained. It should certainly be preferred over `dhclient/avahi-autoipd`).

networkd and NM can fall back to IPv4LL as well.

> deprecate avahi-autoipd in following release

@pemensik I think it should be OK to announce its removal in the release notes to see who cares about that and then remove it and close all the https://github.com/avahi/avahi/labels/autoipd issues. Distros where it's needed to support legacy set-ups can always maintain their own forks downstream and receive and handle bug reports there.
