### ISSUE TITLE
Add cups service disable

### ISSUE THREAD

**Issue by slipttees** [avahi/avahi#570]
So.

There should be an option to disable printer discovery only. This avoids duplicate printers on the network that use cups.

discusion
https://groups.google.com/g/linux.debian.user/c/82hXQAw4WBI

https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1753509

**Comment by evverx** [comment]
Looking at, say,
> This is not a bug of Avahi, Avahi is only handling the DNS-SD broadcasts
...
>  It is GTK you want to control, not avahi-daemon

I wonder what makes you think it's an avahi issue?

> There should be an option to disable printer discovery only

Could you be more specific?

**Comment by evverx** [comment]
I reread those threads and I don't think it makes sense to add knobs like that to avahi. Closing.

**Comment by tycho-kirchner** [comment]
Sorry for necrobumping but as I explained in [my answer on askubuntu.com](https://askubuntu.com/a/1544292) to avoid not installed avahi-detected printers showing up in print-dialogs requires either to disable avahi altogether (which is bad) or patching gtk as well as libcups2. So I'm not blaming avahi specifically for this but I think there should be a _clean_ way for the non-programmer to disable avahi detected printers. On the net there really is a huge list of threads of casual Linux users attempting just this. 
Fixing this in gtk and libcups2 requires two projects to agree -- a disable-option in avahi requires only one. Thus I would like to kindly ask you to reconsider adding this functionality, maybe in form of a `disable`-file, e.g. `/etc/avahi/services/ipp.service.disabled`?
That's at least the "solution" some AI suggested 😅:
> To prevent Avahi from advertising or detecting printers while still allowing
> scanner discovery, you can disable the printer-related service files. For
> example, on many systems the printer services are defined in files such as
> ipp.service or cups.service located in either /etc/avahi/services/ or
> /usr/share/avahi/services/. You can disable these services by renaming them
> (e.g., append “.disabled” to the filename) or moving them out of the directory.
> After making these changes, restart Avahi:

Otherwise I would kindly like to ask if you would support me in convincing the developers of the respective print dialogs to fix that on their end or if you have other suggestions in improving the situation.
Best Regards, Tycho
