### ISSUE TITLE
Fix various wide-area-dns limitations

### ISSUE THREAD

**Issue by pemensik** [avahi/avahi#578]
In PR #577 wide area resolution were disabled. While I admit current state is far from well tested, this feature seems interesting for me. Basic functionality can be tested on *dns-sd.org* and *zeroconf.org* domains.

But I agree combinations between mDNS and (wide-area) DNS need better analysis and maybe at least some design. This is area, where I can offer help. Unicast DNS belongs to my area of expertise.

But it would need multiple limitations fixed. Nothing just one PR with few modifications can fix enough.

**Comment by evverx** [comment]
Agreed. It would be great to support the unicast DNS properly.

There are already issues where some things are tracked: https://github.com/avahi/avahi/issues/239 , https://github.com/avahi/avahi/issues/254 but given that that part effectively hasn't been updated since 2007 (apart from a commit fixing a huge memory leak) it's safe to say that it's far from what DNS looks like today unfortunately.

**Comment by evverx** [comment]
Now that the wide-area label can be used to keep track of existing known issues I don't think it makes sense to keep this umbrella issue. By looking at https://github.com/avahi/avahi/labels/wide-area it should be clear that it doesn't exactly work and can't interact with mDNS well. I'd also add that it isn't tested by the upstream CI at all so any attempts to fix all that stuff should start with covering it with tests. Closing.
