### ISSUE TITLE
Update of sl.po - Slovenian l10n

### ISSUE THREAD

**Issue by filmsi** [avahi/avahi#618]
Here is the updated sl.po file.
[sl.po.zip](https://github.com/user-attachments/files/16403063/sl.po.zip)

**Comment by evverx** [comment]
Thank you! Could you open a PR with a commit message so that the changes could be attributed to you correctly?

(Ideally avahi should be integrated with Weblate: https://github.com/avahi/avahi/issues/603. This way the bot could pull all the changes from there and open PRs automaticall)

**Comment by evverx** [comment]
I took a look at the po file. `Report-Msgid-Bugs-To` should be replaced with https://github.com/avahi/avahi/issues because avahi moved recently: 94e1ffdfbe7a1b7036b9902bab15ea0ef8b24eb4. Also as far as I can see there are a lot of changes like
```diff
-#: ../avahi-common/error.c:30
+#: avahi-common/error.c:30
```
I think it would be better to exclude them for now. All the other po files come with the `../*` path currently so

**Comment by evverx** [comment]
@filmsi avahi was integrated into the Fedora Weblate translation platform and started to pull changes from it: https://github.com/avahi/avahi/pull/625, https://github.com/avahi/avahi/pull/626.

Could you submit the changes via https://translate.fedoraproject.org/engage/avahi/ ?

I'll go ahead and close the issue here because it's tracked on Weblate now.

**Comment by AhmTaher** [comment]
Ahmed 
/chm
